<?php
use CRM_Goonjcustom_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Individual_fields',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Individual_fields',
        'title' => E::ts('Individual fields'),
        'extends' => 'Individual',
        'style' => 'Inline',
        'help_pre' => '',
        'help_post' => '',
        'weight' => 3,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-06-14 13:16:09',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_Original_Registration_Date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'Original_Registration_Date',
        'label' => E::ts('Original Registration Date'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'original_registration_date_48',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_Mobile_Country_Code',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'Mobile_Country_Code',
        'label' => E::ts('Mobile Country Code'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'mobile_country_code_49',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_Status',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Individual_fields_Status',
        'title' => E::ts('Individual fields :: Status'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_Status_OptionValue_Active',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Individual_fields_Status',
        'label' => E::ts('Active'),
        'value' => '1',
        'name' => 'Active',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_Status_OptionValue_Inactive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Individual_fields_Status',
        'label' => E::ts('Inactive'),
        'value' => '2',
        'name' => 'Inactive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_Status',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'Status',
        'label' => E::ts('Status'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'status_62',
        'option_group_id.name' => 'Individual_fields_Status',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_Engagement_Contribution_Date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'Engagement_Contribution_Date',
        'label' => E::ts('Engagement / Contribution Date'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'engagement_contribution_date_120',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_How_do_you_heard_about_Goonj',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Individual_fields_How_do_you_heard_about_Goonj',
        'title' => E::ts('Individual fields :: How do you heard about Goonj'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_How_do_you_heard_about_Goonj_OptionValue_Friend_Family',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Individual_fields_How_do_you_heard_about_Goonj',
        'label' => E::ts('Friend / Family'),
        'value' => '1',
        'name' => 'Friend_Family',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_How_do_you_heard_about_Goonj_OptionValue_Newspaper',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Individual_fields_How_do_you_heard_about_Goonj',
        'label' => E::ts('Newspaper'),
        'value' => '2',
        'name' => 'Newspaper',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_How_do_you_heard_about_Goonj_OptionValue_Website',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Individual_fields_How_do_you_heard_about_Goonj',
        'label' => E::ts('Website'),
        'value' => '3',
        'name' => 'Website',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Individual_fields_How_do_you_heard_about_Goonj_OptionValue_Social_media',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Individual_fields_How_do_you_heard_about_Goonj',
        'label' => E::ts('Social media'),
        'value' => 'Social media',
        'name' => 'Social_media',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_How_do_you_heard_about_Goonj',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'How_do_you_heard_about_Goonj',
        'label' => E::ts('How do you heard about Goonj'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'how_do_you_heard_about_goonj_257',
        'option_group_id.name' => 'Individual_fields_How_do_you_heard_about_Goonj',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_Created_Date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'Created_Date',
        'label' => E::ts('Created Date'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'MM d, yy',
        'time_format' => 1,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'created_date_206',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Individual_fields_CustomField_Source_Processing_Center',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Individual_fields',
        'name' => 'Source_Processing_Center',
        'label' => E::ts('Source Processing Center'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'source_processing_center_255',
        'fk_entity' => 'Contact',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
