<?php
use CRM_Goonjcustom_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Material_Contribution',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Material_Contribution',
        'title' => E::ts('Material Contribution'),
        'extends' => 'Activity',
        'extends_entity_column_value' => [
          '63',
        ],
        'style' => 'Inline',
        'help_pre' => '',
        'help_post' => '',
        'weight' => 13,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-08-21 09:34:04',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak',
        'title' => E::ts('Material Contribution :: Do you wish to take a Goonj Ke Gullak or return a filled Gullak?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak_OptionValue_Took_an_empty_Gullak',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak',
        'label' => E::ts('Took an empty Gullak'),
        'value' => '1',
        'name' => 'Took_an_empty_Gullak',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak_OptionValue_Returned_a_filled_Gullak',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak',
        'label' => E::ts('Returned a filled Gullak'),
        'value' => '2',
        'name' => 'Returned_a_filled_Gullak',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak_OptionValue_None',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak',
        'label' => E::ts('None'),
        'value' => '3',
        'name' => 'None',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Do_you_wish_to_take_a_Goonj_Ke_Gullak_or_return_a_filled_Gullak_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Do_you_wish_to_take_a_Goonj_Ke_Gullak_or_return_a_filled_Gullak_',
        'label' => E::ts('Do you wish to take a Goonj Ke Gullak or return a filled Gullak?'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'do_you_wish_to_take_a_goonj_ke_g_115',
        'option_group_id.name' => 'Material_Contribution_Do_you_wish_to_take_a_Goonj_Ke_Gullak',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Do_You_wish_to_do_Monetary_Money_Contribution_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Do_You_wish_to_do_Monetary_Money_Contribution_',
        'label' => E::ts('Do You wish to do Monetary/Money Contribution ?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'do_you_wish_to_do_monetary_money_117',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Type_of_Contribution',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Material_Contribution_Type_of_Contribution',
        'title' => E::ts('Material Contribution :: Type of Contribution'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Type_of_Contribution_OptionValue_Material',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Material_Contribution_Type_of_Contribution',
        'label' => E::ts('Material'),
        'value' => '1',
        'name' => 'Material',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Type_of_Contribution_OptionValue_Monetary',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Material_Contribution_Type_of_Contribution',
        'label' => E::ts('Monetary'),
        'value' => '2',
        'name' => 'Monetary',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Material_Contribution_Type_of_Contribution_OptionValue_Both',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Material_Contribution_Type_of_Contribution',
        'label' => E::ts('Both'),
        'value' => '3',
        'name' => 'Both',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Type_of_Contribution',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Type_of_Contribution',
        'label' => E::ts('Type of Contribution'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'type_of_contribution_119',
        'option_group_id.name' => 'Material_Contribution_Type_of_Contribution',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Collection_Camp',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Collection_Camp',
        'label' => E::ts('Collection Camp'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'collection_camp_210',
        'fk_entity' => 'Eck_Collection_Camp',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Goonj_Office',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Goonj_Office',
        'label' => E::ts('Goonj Office'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'goonj_office_213',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Institute_Registration_Type_of_Institution',
        'title' => E::ts('Institute Registration :: Type of Institution'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Hospital',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Hospital'),
        'value' => 'Hospital',
        'name' => 'Hospital',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_NGO',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('NGO'),
        'value' => 'NGO',
        'name' => 'NGO',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Others',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Others'),
        'value' => 'Others',
        'name' => 'Others',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Boutique_Tailor',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Boutique/ Tailor'),
        'value' => 'Boutique/ Tailor',
        'name' => 'Boutique_Tailor',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Colleges_University_Institute',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Colleges/University/Institute'),
        'value' => 'Colleges/University/Institute',
        'name' => 'Colleges_University_Institute',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Corporate',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Corporate'),
        'value' => 'Corporate',
        'name' => 'Corporate',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Government_Entity',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Government Entity'),
        'value' => 'Government Entity',
        'name' => 'Government_Entity',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Hotel',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Hotel'),
        'value' => 'Hotel',
        'name' => 'Hotel',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Individual',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Individual'),
        'value' => 'Individual',
        'name' => 'Individual',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Entity_Type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Entity_Type',
        'label' => E::ts('Entity Type'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'entity_type_238',
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Entity_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Entity_Name',
        'label' => E::ts('Entity Name'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'entity_name_239',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Delivered_By',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Delivered_By',
        'label' => E::ts('Delivered By: Name'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'delivered_by_240',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Material_Contribution_CustomField_Delivered_By_Contact',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Material_Contribution',
        'name' => 'Delivered_By_Contact',
        'label' => E::ts('Delivered By: Contact'),
        'data_type' => 'Float',
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'delivered_by_contact_241',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
