<?php
use CRM_Goonjcustom_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Office_Visit',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Office_Visit',
        'title' => E::ts('Office Visit'),
        'extends' => 'Activity',
        'extends_entity_column_value' => [
          '65',
        ],
        'style' => 'Inline',
        'help_pre' => '',
        'help_post' => '',
        'weight' => 19,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-08-28 18:27:58',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Office_Visit_Purpose',
        'title' => E::ts('Office Visit :: Purpose'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Volunteering',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Volunteering'),
        'value' => 'Volunteering',
        'name' => 'Volunteering',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Internship',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Internship'),
        'value' => 'Internship',
        'name' => 'Internship',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Exposure',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Exposure'),
        'value' => 'Exposure',
        'name' => 'Exposure',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Interview',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Interview'),
        'value' => 'Interview',
        'name' => 'Interview',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Fellowship',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Fellowship'),
        'value' => 'Fellowship',
        'name' => 'Fellowship',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Only_visit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Only visit'),
        'value' => 'Only visit',
        'name' => 'Only_visit',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Material_Contribution',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Material Contribution'),
        'value' => 'Material Contribution',
        'name' => 'Material_Contribution',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Meeting',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Meeting'),
        'value' => 'Meeting',
        'name' => 'Meeting',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Research',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Research'),
        'value' => 'Research',
        'name' => 'Research',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Videography',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Videography'),
        'value' => 'Videography',
        'name' => 'Videography',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_Purpose_OptionValue_Other',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_Purpose',
        'label' => E::ts('Other'),
        'value' => 'Other',
        'name' => 'Other',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Purpose',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Purpose',
        'label' => E::ts('Purpose Of Visit'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'purpose_207',
        'option_group_id.name' => 'Office_Visit_Purpose',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_How_do_you_heard_about_Goonj',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'How_do_you_heard_about_Goonj',
        'label' => E::ts('How do you heard about Goonj'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'how_do_you_heard_about_goonj_208',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Would_You_Like_to_Receive_Updates_from_Us_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Would_You_Like_to_Receive_Updates_from_Us_',
        'label' => E::ts('Would You Like to Receive Updates from Us?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'would_you_like_to_receive_update_209',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_You_are_Visiting_as',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Office_Visit_You_are_Visiting_as',
        'title' => E::ts('Office Visit :: You are Visiting as'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_You_are_Visiting_as_OptionValue_Individual',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_You_are_Visiting_as',
        'label' => E::ts('Individual'),
        'value' => 'Individual',
        'name' => 'Individual',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Office_Visit_You_are_Visiting_as_OptionValue_Group',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Office_Visit_You_are_Visiting_as',
        'label' => E::ts('Group'),
        'value' => 'Group',
        'name' => 'Group',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_You_are_Visiting_as',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'You_are_Visiting_as',
        'label' => E::ts('You are Visiting as'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'you_are_visiting_as_234',
        'option_group_id.name' => 'Office_Visit_You_are_Visiting_as',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Institute_Registration_Type_of_Institution',
        'title' => E::ts('Institute Registration :: Type of Institution'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Hospital',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Hospital'),
        'value' => 'Hospital',
        'name' => 'Hospital',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_NGO',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('NGO'),
        'value' => 'NGO',
        'name' => 'NGO',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Others',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Others'),
        'value' => 'Others',
        'name' => 'Others',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Boutique_Tailor',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Boutique/ Tailor'),
        'value' => 'Boutique/ Tailor',
        'name' => 'Boutique_Tailor',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Colleges_University_Institute',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Colleges/University/Institute'),
        'value' => 'Colleges/University/Institute',
        'name' => 'Colleges_University_Institute',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Corporate',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Corporate'),
        'value' => 'Corporate',
        'name' => 'Corporate',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Government_Entity',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Government Entity'),
        'value' => 'Government Entity',
        'name' => 'Government_Entity',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Hotel',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Hotel'),
        'value' => 'Hotel',
        'name' => 'Hotel',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Institute_Registration_Type_of_Institution_OptionValue_Individual',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
        'label' => E::ts('Individual'),
        'value' => 'Individual',
        'name' => 'Individual',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Entity_Type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Entity_Type',
        'label' => E::ts('Entity Type'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'entity_type_242',
        'option_group_id.name' => 'Institute_Registration_Type_of_Institution',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Entity_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Entity_Name',
        'label' => E::ts('Entity Name'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'entity_name_243',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Other_Entity_Type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Other_Entity_Type',
        'label' => E::ts('Other Entity Type'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'other_entity_type_244',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Goonj_Processing_Center',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Goonj_Processing_Center',
        'label' => E::ts('Goonj Processing Center'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'goonj_processing_center_245',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Office_Visit_CustomField_Visit_Taken_By_Goonj_Member_Name_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Office_Visit',
        'name' => 'Visit_Taken_By_Goonj_Member_Name_',
        'label' => E::ts('Visit Taken By (Goonj Member Name)'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'visit_taken_by_goonj_member_name_246',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
