<?php
use CRM_Goonjcustom_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Details',
        'title' => E::ts('Intent Details'),
        'extends' => 'Eck_Collection_Camp',
        'extends_entity_column_value' => [
          '1',
        ],
        'style' => 'Inline',
        'help_pre' => '',
        'help_post' => '',
        'weight' => 15,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-08-22 14:47:46',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Location_Area_of_camp',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Location_Area_of_camp',
        'label' => E::ts('Location/Area of camp'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'location_area_of_camp_123',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_District',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'District',
        'label' => E::ts('District'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'district_126',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Start_Date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Start_Date',
        'label' => E::ts('Start Date'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'time_format' => 1,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'start_date_127',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_End_Date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'End_Date',
        'label' => E::ts('End Date'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'time_format' => 1,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'end_date_128',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Are_the_details_confirmed_wi',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Details_Are_the_details_confirmed_wi',
        'title' => E::ts('Collection Camp Intent Details :: Are the details confirmed with the volunteer?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Are_the_details_confirmed_wi_OptionValue_Yes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Are_the_details_confirmed_wi',
        'label' => E::ts('Yes'),
        'value' => '1',
        'name' => 'Yes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Are_the_details_confirmed_wi_OptionValue_No',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Are_the_details_confirmed_wi',
        'label' => E::ts('No'),
        'value' => '2',
        'name' => 'No',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Are_the_details_confirmed_with_the_volunteer_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Are_the_details_confirmed_with_the_volunteer_',
        'label' => E::ts('Are the details confirmed with the volunteer?'),
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'are_the_details_confirmed_with_t_129',
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Are_the_details_confirmed_wi',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'title' => E::ts('Collection Camp Intent Details :: You wish to register as'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_An_authority_from_the_society',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('An authority from the society'),
        'value' => '1',
        'name' => 'An_authority_from_the_society',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_Residents_Welfare_Association_R',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('Residents Welfare Association (RWA)'),
        'value' => '2',
        'name' => 'Residents_Welfare_Association_R',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_Resident_of_the_society',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('Resident of the society'),
        'value' => '3',
        'name' => 'Resident_of_the_society',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_A_Corporate_organisation',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('A Corporate organisation'),
        'value' => '4',
        'name' => 'A_Corporate_organisation',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_A_School',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('A School'),
        'value' => '5',
        'name' => 'A_School',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_A_College_University',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('A College/University'),
        'value' => '6',
        'name' => 'A_College_University',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_An_individual',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('An individual'),
        'value' => '7',
        'name' => 'An_individual',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_You_wish_to_register_as_OptionValue_Other',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
        'label' => E::ts('Other'),
        'value' => '8',
        'name' => 'Other',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_You_wish_to_register_as',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'You_wish_to_register_as',
        'label' => E::ts('You wish to register as'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'you_wish_to_register_as_131',
        'option_group_id.name' => 'Collection_Camp_Intent_Details_You_wish_to_register_as',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_City',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'City',
        'label' => E::ts('City'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'city_132',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Name',
        'label' => E::ts('Name'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'name_133',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Contact_Number',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Contact_Number',
        'label' => E::ts('Contact Number'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'contact_number_134',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Pin_Code',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Pin_Code',
        'label' => E::ts('Pin Code'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pin_code_135',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Is_there_any_Logo_to_be_added_in_the_Leaflet_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Is_there_any_Logo_to_be_added_in_the_Leaflet_',
        'label' => E::ts('Is there any Logo to be added in the Leaflet?'),
        'data_type' => 'File',
        'html_type' => 'File',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'is_there_any_logo_to_be_added_in_137',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Do_you_require_permission_le',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Details_Do_you_require_permission_le',
        'title' => E::ts('Collection Camp Intent Details :: Do you require permission letters from Goonj to get permission from authorities for organizing camps?'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Do_you_require_permission_le_OptionValue_Yes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Do_you_require_permission_le',
        'label' => E::ts('Yes'),
        'value' => '1',
        'name' => 'Yes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Do_you_require_permission_le_OptionValue_No',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Do_you_require_permission_le',
        'label' => E::ts('No'),
        'value' => '2',
        'name' => 'No',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Do_you_require_permission_letters_from_Goonj_to_get_permission_f',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Do_you_require_permission_letters_from_Goonj_to_get_permission_f',
        'label' => E::ts('Do you require permission letters from Goonj to get permission from authorities for organizing camps?'),
        'data_type' => 'Int',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'do_you_require_permission_letter_139',
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Do_you_require_permission_le',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati',
        'title' => E::ts('Collection Camp Intent Details :: Do you want to plan a creative and engaging activity where residents can connect in ways that go beyond just giving material?'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati_OptionValue_Yes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati',
        'label' => E::ts('Yes'),
        'value' => '1',
        'name' => 'Yes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati_OptionValue_No',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati',
        'label' => E::ts('No'),
        'value' => '2',
        'name' => 'No',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Do_you_want_to_plan_a_creative_and_engaging_activity_where_resid',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Do_you_want_to_plan_a_creative_and_engaging_activity_where_resid',
        'label' => E::ts('Do you want to plan a creative and engaging activity where residents can connect in ways that go beyond just giving material?'),
        'data_type' => 'Int',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'do_you_want_to_plan_a_creative_a_141',
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Do_you_want_to_plan_a_creati',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Camp_Type',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Details_Camp_Type',
        'title' => E::ts('Collection Camp Intent Details :: Camp Type'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Camp_Type_OptionValue_IHC',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Camp_Type',
        'label' => E::ts('IHC'),
        'value' => '1',
        'name' => 'IHC',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Details_Camp_Type_OptionValue_PCC',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Camp_Type',
        'label' => E::ts('PCC'),
        'value' => '2',
        'name' => 'PCC',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Camp_Type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Camp_Type',
        'label' => E::ts('Camp Type'),
        'data_type' => 'Int',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'camp_type_142',
        'option_group_id.name' => 'Collection_Camp_Intent_Details_Camp_Type',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Other_activity',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Other_activity',
        'label' => E::ts('Other activity'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'other_activity_144',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Reason_For_Unauthorize',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Collection_Camp_Intent_Reason_For_Unauthorize',
        'title' => E::ts('Collection Camp Intent :: Reason For Unauthorize'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Reason_For_Unauthorize_OptionValue_Option_1',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Reason_For_Unauthorize',
        'label' => E::ts('Option 1'),
        'value' => '1',
        'name' => 'Option_1',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Collection_Camp_Intent_Reason_For_Unauthorize_OptionValue_Option_2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Collection_Camp_Intent_Reason_For_Unauthorize',
        'label' => E::ts('Option 2'),
        'value' => '2',
        'name' => 'Option_2',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Reason_For_Unauthorize',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Reason_For_Unauthorize',
        'label' => E::ts('Reason For Unauthorize'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'reason_for_unauthorize_148',
        'option_group_id.name' => 'Collection_Camp_Intent_Reason_For_Unauthorize',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Campaign',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Campaign',
        'label' => E::ts('Campaign'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'campaign_149',
        'fk_entity' => 'Campaign',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'title' => E::ts('Intent Details :: Here are some activities to pick from, but feel free to invent your own!'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Bake_Sale',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Bake & Sale'),
        'value' => '1',
        'name' => 'Bake_Sale',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Tea_sale',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Tea sale'),
        'value' => '2',
        'name' => 'Tea_sale',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Gullak_making',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Gullak making'),
        'value' => '3',
        'name' => 'Gullak_making',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Sports_activity',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Sports activity'),
        'value' => '4',
        'name' => 'Sports_activity',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Make_sale',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Make & sale'),
        'value' => '5',
        'name' => 'Make_sale',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Lemonade_sale',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Lemonade sale'),
        'value' => '6',
        'name' => 'Lemonade_sale',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Here_are_some_activities_to_pick_from_but_fe_OptionValue_Others',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'label' => E::ts('Others'),
        'value' => '7',
        'name' => 'Others',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Here_are_some_activities_to_pick_from_but_feel_free_to_invent_yo',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Here_are_some_activities_to_pick_from_but_feel_free_to_invent_yo',
        'label' => E::ts('Here are some activities to pick from, but feel free to invent your own!'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'here_are_some_activities_to_pick_154',
        'option_group_id.name' => 'Intent_Details_Here_are_some_activities_to_pick_from_but_fe',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Goonj_Office',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Goonj_Office',
        'label' => E::ts('Goonj Office'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'goonj_office_216',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Coordinating_Urban_POC',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Coordinating_Urban_POC',
        'label' => E::ts('Coordinating Urban POC'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'coordinating_urban_poc_233',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Associated_activities_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Intent_Details_Associated_activities_',
        'title' => E::ts('Intent Details :: Associated activities?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Associated_activities_OptionValue_Lemonade',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Associated_activities_',
        'label' => E::ts('Lemonade'),
        'value' => '1',
        'name' => 'Lemonade',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Associated_activities_OptionValue_Gullak',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Associated_activities_',
        'label' => E::ts('Gullak'),
        'value' => '2',
        'name' => 'Gullak',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Associated_activities_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Associated_activities_',
        'label' => E::ts('Associated activities?'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'associated_activities__260',
        'option_group_id.name' => 'Intent_Details_Associated_activities_',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_State',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Intent_Details_State',
        'title' => E::ts('Intent Details :: State'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_State',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'State',
        'label' => E::ts('State'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'state_261',
        'option_group_id.name' => 'Intent_Details_State',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Will_your_collection_drive_be_open_for_gener',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Intent_Details_Will_your_collection_drive_be_open_for_gener',
        'title' => E::ts('Intent Details :: Will your collection drive be open for general public'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Will_your_collection_drive_be_open_for_gener_OptionValue_Yes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Will_your_collection_drive_be_open_for_gener',
        'label' => E::ts('Yes'),
        'value' => '2',
        'name' => 'Yes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Intent_Details_Will_your_collection_drive_be_open_for_gener_OptionValue_No',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Intent_Details_Will_your_collection_drive_be_open_for_gener',
        'label' => E::ts('No'),
        'value' => '1',
        'name' => 'No',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Collection_Camp_Intent_Details_CustomField_Will_your_collection_drive_be_open_for_general_public',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Collection_Camp_Intent_Details',
        'name' => 'Will_your_collection_drive_be_open_for_general_public',
        'label' => E::ts('Will your collection drive be open for general public'),
        'data_type' => 'Int',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'will_your_collection_drive_be_op_262',
        'option_group_id.name' => 'Intent_Details_Will_your_collection_drive_be_open_for_gener',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
